[env:esp32-c3]
platform = espressif32
; Module tren mach ghi "ESP32-C3-MINI-V1" -> dung devkit generic cua Espressif,
; hoat dong tot voi hau het board rong ESP32-C3 vi khong dung define theo board.
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 9600
build_flags =
    -I../shared
